### ISSUE TITLE
jar file non existent 

### ISSUE THREAD

**Issue by zuble** [datcuandrei/BackToMac#2]
Hello

How can i build the .jar file ? Tried a workaround and quickie way with JAR builder in vscode but not getting any results. Not really into java:/

Thanks in advance.

**Comment by datcuandrei** [comment]
Hi, zuble!

First of all, it is required that you have IntelliJ IDEA installed on your computer; the whole project was built in it. You can only build it Using IDEA's compiler.

Regards,
AD.

**Comment by zuble** [comment]
So i ended not compiling from source although the following error occur when executing the app.

![imagem](https://user-images.githubusercontent.com/67658465/150893492-eb85b40d-3e5e-4094-89d8-33118b1ed3ee.png)

From what i searched the cause of the error is that different versions of java were used in compile and run.

So the solution is to compile from myself ? How should the project be open and build ? Any special configure in IDEA ?
